# Created using wingetcreate 1.10.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: SmartSoft.SmartFTP
PackageVersion: 10.0.3276.0
MinimumOSVersion: 10.0.17763.0
Installers:
- InstallerLocale: en-US
  Platform:
  - Windows.Desktop
  Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://static.smartftp.com/static/Products/Client/10.0.3276.0/x64/SmartFTP.msi
  InstallerSha256: 22753B6ADA03A6378D5A706CE522734D4795A593DB14F9D34A812135A5509C03
  ProductCode: '{C556547A-80A0-49CD-B213-7DFC743CA147}'
  UnsupportedOSArchitectures:
  - arm64
  AppsAndFeaturesEntries:
  - UpgradeCode: '{2119EFC7-B9BF-445D-9DB9-A9052E8391C5}'
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2025-07-11
