# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: SmartSoft.SmartFTP
PackageVersion: 10.0.3268.0
MinimumOSVersion: 10.0.17763.0
Installers:
- InstallerLocale: en-US
  Platform:
  - Windows.Desktop
  Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://static.smartftp.com/static/Products/Client/10.0.3268.0/x64/SmartFTP.msi
  InstallerSha256: 2F44A9C87F1EB801BB3525791F851EBE56C27FFE47DDF4C62A20D284BFDAF8DE
  ProductCode: '{AAFB10FA-4E56-4897-9E3B-3505E284A6AD}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{2119EFC7-B9BF-445D-9DB9-A9052E8391C5}'
ManifestType: installer
ManifestVersion: 1.5.0
ReleaseDate: 2025-04-25
